### ISSUE TITLE
Thoughts on placements of several things. 

### ISSUE THREAD

**Issue by JamesSkyminer** [weblue/weblue.github.io#14]
I figured I'd go through the list and point out a few problems I had with the variety of weapons. 

Primaries:

* Tonkor is easily not top tier anymore. I'd say it's easily "viable," but it doesn't deserve to be in the same tier as Lenz.  

* You said vanilla Quanta is top tier? Gonna assume that's a typo.

* Dex Sybaris is basically on-par with Soma Prime. It should be top tier. 

* As much as I love Ignis Wraith, it doesn't deserve to be top tier. It's not that much better than the normal Ignis. 

* Convectrix is non-viable.

* Have you actually bothered to use Synoid Simulor after its "nerf"? It's still quite good, you just can't use it in the mindless way you used to be able to. It's easily viable at the very least. Think of it more as a grenade launcher you can use at close range.

* Latron Wraith and Prime ought to low-viable.

Secondaries:

* Sicarus Prime and Arca Scisco are both easily top tier (saw them in untested). 

* As for another untested, Zakti probably deserves to be top tier. Although I think Zakti needs it to be mentioned that it really shines when dual-wielded with a Glaive. Without that, it's only viable. 

* I'd put Synoid Gammacor in middle viable. Dex Furis easily outperforms it. 

* I would put Lato, Aklato, or Embolist all in non-viable. 

* Vasto Prime's buff makes it deserve top tier now. It's a crit/status hybrid that's slash focused.  

Melee:

* If you're gonna put Destreza in top tier...the whole horde of amazing dual swords would like a word with you. 

* Sarpa is actually best built for status with condition overload. Unlike Redeemer, its pellets DONT split up for status, and with weeping wounds in the mix it quickly decimates anything once it gets a combo going. 

* If we're taking utility weapons like Sonicor into account as top-tier...I'd say Zenistar deserves a place in top tier. It can effectively lock down an entire area for the duration of its disc being out. Make a Gas+Electric build and it'll poison everything in the area as well as CC them. 

No arguments with Archguns/Archmelee. 

Companions: 

* Adarza Kavat is easily top tier for pets. +60% crit for all teammates in range effectively makes it a mini Harrow. 

* I wouldn't put Diriga in top tier if Prisma Shade isn't tbh. Prisma Shade has the virtue of being the second tankiest sentinel in the game (after carrier p).

**Comment by weblue** [comment]
Revisions:

Tonkor to be moved to Mid Viable tier

Vanilla Quanta to Low Viable tier

Dex Sybaris up for review

Ignis Wraith to Low Top tier

Convectrix to high Non-Viable tier

Synoid Simulor to be keep current position however notes will be modified to outline the use case

Latron Wraith for review

Synoid Gammacor for review

Lato, Aklato, to non-viable

Vasto Prime for review

Destreza for review

Sarpa for review

Zenistar for review

Adarza Kavat for review

I'd like clarification for Prisma Shade

**Comment by weblue** [comment]
Thank you for making an account on GitHub for the purpose of suggesting improvements to the list. Your efforts are very appreciated and not unnoticed.

Now that I've reviewed your suggestions, if you're the person who made the same reddit comment and then caused a shit storm to come down on me for wanting to use Github Issues: stop being a cunt. If you asked me why I wanted to ignore reddit comments for direct feedback to the list, you'd know that I like having checkboxes and assigning changes to the next revision. Github issues gives me a way to directly and transparently address issues with users of the list, give them responses to their feedback, assign another tester to a problem or promote generally good discussion along the lines of a single change. None of these features are offered on reddit, but because of the reddit response and the massive downvoting, I have to type in redditor's feedback to rankings myself into here.

The tierlist was work of love and took a bunch of time and effort from me to be used as a resource by me and other players. If you're going to criticize features of the list, you'd better have as much passion and effort in those criticisms as I put into the list.

**Comment by weblue** [comment]
If you're not the same redditor, ignore the middle paragraph

**Comment by JamesSkyminer** [comment]
I posted my thoughts on the entire thing after reading through *literally  everything* after clicking on the thread only like a minute after it was posted. I never saw your comment about not wanting reddit comments discussing things because *it didn't exist yet* as I was on a completely blank post as i was going through everything and typing out my thoughts to help you. 

Your response was what got everything downvoted, because it made it look like you were simply trying to avoid anything that looked like criticism and tbh it largely made the point of reviewing a tierlist you're still working on seem kind of irrelevant. The mods pointed out that it broke Reddit's rules, I simply had made points to help because I understand how much work goes into stuff like this.

**Comment by weblue** [comment]
The whole point of this tierlist is it's curated but community managed, just like it was 3 years ago.

It didn't break reddit's rules because it wasn't avoiding discussion, I said to use Github's feature specifically for item rankings. Discussing anything about the website itself or the technologies behind it would've been fine.

Either way, all of the related stuff was deleted and I'll publish it again at a better time instead of 1am on a Sunday.

I actively encourage help with rankings and appreciate the effort to comment and respond, but I took your comments as condescending and got defensive when I got downvoted.

Also, I still need clarification on why Prisma Shade should be moved. Diriga provides CC while Prisma Shade is just tanky; why should Shade be moved?

**Comment by JamesSkyminer** [comment]
Shade can provide invisibility, which can be a huge help for doing things like reviving teammates...although admittedly this is something you can do with operator mode. But even so, being cloaked during a reload cycle or just for ability casting isn't something to scoff at...and if you're doing any long missions, you take any survivability for your sentinel that you can. But most importantly it can cloak you during offense abilities, most notably something like Banshee's Soundquake, where the cloak can be the difference between you living or dying due to the long animation to get out of using it.

**Comment by weblue** [comment]
Tonkor to rank 27, Viable
Ignis Wraith to rank 20, Top
Synoid Simular notes edited
Vanilla Quanta to Non-Viable
and all others in primaries have been moved

**Comment by weblue** [comment]
Vasto Prime to high Viable tier (this may change as I work with the builds, but it feels about right in this spot now, imo)

Embolist, Lato, Aklato to Non-Viable tier

Synoid Gammacor to high Viable tier

Untested stuff is going to be reserved for an update after reviewing melees

**Comment by weblue** [comment]
Adarza Kavat to top tier

Wyrm Prime unchanged

While Wyrm Prime's constitution is definitely great, the issue comes in when it comes to how dependability of the stun. Controlling when to use the stun makes using the sentinel a bit clunky.

**Comment by JamesSkyminer** [comment]
I'd be happy to join the discord btw.

**Comment by weblue** [comment]
Destreza is unchanged, however there's a lot of dual sword already at the top of the Viable tier; I feel these are all in the correct spot

Sarpa and Redeemer's notes have been updated to reflect what you've said here, however they're at their current ranks because of issues with accuracy and range

Zenistar was definitely in the wrong spot, it's been moved to the top of Viable tier and may change go higher over time

Prisma Shade is extremely beefy, but the effective health is wasted on a sentinel who's ability is to turn invisible. It is strong on paper, but Diriga's stunlock mechanic blows the usefulness of Shade out of the water

The discord link is here if you'd like to discuss more https://discord.gg/Cq3jW27

Looking forward to hearing more from you!

Thank you for all the input, I'm closing this issue out

**Comment by JamesSkyminer** [comment]
A note on Sarpa vs Redeemer: what I said only affects Sarpa. Redeemer's
shots are in fact shotgun-blasts, and therefore suffer from the same issues
are shotguns for status.Sarpa on the other hand doesn't have innate
multishot, shooting 3 shots in quick succession. Additionally Redeemer's
base damage for the shot is Blast, whereas Sarpa's is I/P/S with a 70%
weight to slash damage. So Sarpa ends up being significantly stronger with
a CondOver build.

**Comment by weblue** [comment]
I understand the distinction, I used what you said to update the notes on the Redeemer and the the Sarpa. However, I still don't see the Sarpa being able to beat out the Glaives in condition builds; because of that, I can't really move it up, but it is above the Redeemer

**Comment by weblue** [comment]
Sicarus Prime and Arca Scisco to top tier
Zakti to Viable
