### ISSUE TITLE
Testing method should be documented

### ISSUE THREAD

**Issue by Bilge** [weblue/weblue.github.io#32]
It's hard to know whether this is just another subjective list or whether an objective testing method was used, since there is no documentation as to how results were observed or recorded. If there is any validity to this list whatsoever, the testing method used should be clearly documented on the site. It would also be a good idea to supplement such a description with any raw data that was recorded as evidence that the testing method was carried out correctly.

**Comment by weblue** [comment]
Since each situation for a weapon can vary by significant amounts, there's no standard for testing. However, Sakai4eva documents his testing process and frequently includes videos as well as documentation when testing and ranking weapons.
The list is as objective as we can make a tier list, but we encourage community members to observe and constructively scrutinize testing and rank placements of weapons.

**Comment by Bilge** [comment]
That's a really terrible answer, and in no way does it preclude the need to expound your testing method. I don't know who "Sakai4eva" is, but if that's the method you're using and if it is documented as you claim, why can you not simply copy in or link to the details of that method?

**Comment by weblue** [comment]
The discord is linked and where would you suggest we copy it in?

**Comment by Bilge** [comment]
It's your website, I'm not going to tell you how to present it.
